### ISSUE TITLE
Add optional hostAliases to values.yaml

### ISSUE THREAD

**Issue by liavyona** [cyberark/secrets-provider-for-k8s#289]
## Is your feature request related to a problem? Please describe.
When using Conjur OSS helm charm in EKS for example, helm generates the certificate for the Conjur server if not provided by user. The certificate will be related to some DNS names such as `{{ Release.name }}`, `{{ Release.name }}.{{ Release.namesapce }}`, , `{{ Release.name }}.{{ Release.namesapce }}.svc` and `{{ .Values.ssl.hostname }}`.

The problem is when enabling external service for Conjur ` {{ Values.service.external.enabled }}`, the ELB for the Conjur will have a random URL generated by AWS (`https://a6b74d226668a4f69baed82f1acee1a3-1525512072.eu-central-1.elb.amazonaws.com`). When passing the ELB url and the `conjur.pem` the SecretProvider will fail due to a discrepancy between the hostname of the URL and the DNS names from the certificate.
![image](https://user-images.githubusercontent.com/31516429/105961132-c744ef80-6086-11eb-99b5-5b5e9f91584a.png)

As Conjur OSS helm chart enables me to control a custom hostname (DNS name for the certificate), I would like to add a new entity to `/etc/hosts` with the custom name and the actual ip address of the ELB url so I can use the SecretProvider with Conjur url as the custom name I control.

## Describe the solution you would like
Under Job.spec.template.spec add the following optional (using `values.yaml`) the hostAliases:
```yaml
    spec:
    {{ if .Values.environment.conjur.domain }}
      hostAliases:
        - ip: {{ .Values.environment.conjur.ip}}
          hostnames:
          - {{ .Values.environment.conjur.domain}}
     {{ end }}
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
```
The result:
```yaml
    spec:
      hostAliases:
        - ip: "35.158.250.20"
          hostnames:
          - "custom.domainname.com"
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
```
## Additional context
While the actual URL of Conjur is `https://a6b74d226668a4f69baed82f1acee1a3-1525512072.eu-central-1.elb.amazonaws.com`, I have the `custom.domainname.com` as a DNS name, so I passed the configuration above and the following values:
```yaml
  conjur:
    # DAP/Conjur account name as defined during initial DAP/Conjur configuration.
    account: cyberark
    # URL of service defined for DAP Follower/Conjur.
    applianceUrl: https://custom.domainname.com
    # URL for the Kubernetes authenticator with which the Secrets Provider will authenticate.
    authnUrl: https://custom.domainname.com/authn-k8s/prod
    # Host that authenticates Secrets Provider to DAP/Conjur.
    authnLogin: host/conjur/authn-k8s/prod/apps/secret-provider-host
```
And got the following result:
![image](https://user-images.githubusercontent.com/31516429/105960989-9ebcf580-6086-11eb-8cac-dbb1603045e4.png)
![image](https://user-images.githubusercontent.com/31516429/105961021-a7153080-6086-11eb-82cc-de1be45ff734.png)
