### ISSUE TITLE
Add k8s config files to the doc

### ISSUE THREAD

**Issue by orenbm** [cyberark/secrets-provider-for-k8s#48]
https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Integrations/Kubernetes_deployApplicationsConjur-k8s-Secrets.htm

Some of the yml files in the docs that create k8s resources are OpenShift orientated and will not work in kubernetes (e.g `DeploymentConfig`). 

We need to update the docs to have also k8s examples.

We can take examples from our tests and also from here: https://conjurhq.slack.com/archives/C2V5T1NRZ/p1575405512465400

**Comment by sigalsax** [comment]
**Configure Kubernetes RBAC permissions**
```
# conjur-role.yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: < TEST_APP_NAMESPACE_NAME >
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: < TEST_APP_NAMESPACE_NAME >
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: < TEST_APP_NAMESPACE_NAME >
    name: < TEST_APP_NAMESPACE_NAME >
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-access
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app-conjur-authenticator-role-binding-< CONJUR_NAMESPACE_NAME >
  namespace: < TEST_APP_NAMESPACE_NAME >
subjects:
  - kind: ServiceAccount
    name: < CONJUR_SERVICE_ACCOUNT >
    namespace: < CONJUR_NAMESPACE_NAME >
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-< CONJUR_NAMESPACE_NAME >
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "patch" ]
```

**Application manifest example**
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: < TEST_APP_NAMESPACE_NAME  >
      containers:
        - image: < TEST_APP_DOCKER_IMAGE >
          imagePullPolicy: Always
          name: test-app
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      initContainers:
        - image: 'cyberark/secrets-provider-for-k8s'
          imagePullPolicy: Always
          name: cyberark-secrets-provider
          env:
            - name: CONTAINER_MODE
              value: init

            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name

            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace

            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: CONJUR_VERSION
              value: '5'

            - name: CONJUR_APPLIANCE_URL
              value: >-
                < CONJUR_APPLIANCE_URL >

            - name: CONJUR_AUTHN_URL
              value: >-
                < CONJUR_AUTHN_URL >

            - name: CONJUR_ACCOUNT
              value: < CONJUR_ACCOUNT >

            - name: CONJUR_AUTHN_LOGIN
              value: >-
                < CONJUR_AUTHN_LOGIN >/test-app

            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  name: < CONFIG_MAP_NAME >
                  key: ssl-certificate

            - name: K8S_SECRETS
              value: db-credentials

            - name: SECRETS_DESTINATION
              value: k8s_secrets
```
